Set initial progress to 0
kukhariev/ngx-uploadx pull request #368
Opened 2022-04-07 21:27 UTC by kontrollanten

For convenient usage, set initial progress to 0 to let the consumer to skip to check if progress isn't NaN.

2022-04-07 21:58 UTC, kukhariev requested changes
progress = 0

2022-04-07 21:58 UTC, kukhariev commented on src/uploadx/lib/uploader.ts
> +  progress: number = 0;
```ts
progress = 0
```

2022-04-07 21:58 UTC, kukhariev commented on src/uploadx/lib/uploader.ts
> +  progress: number = 0;
Thanks!

2022-04-07 22:12 UTC, kukhariev approved these changes

2022-04-07 22:14 UTC, merged

2022-04-19 12:41 UTC, Chocobozzz commented
`offset` should also be initialized to not have `NaN` in `uploading` state

2022-04-19 15:55 UTC, kukhariev commented
@Chocobozzz 
I'm not sure to understand: `offset: number | undefined` is internal, not a member of `UploadState`.

https://github.com/kukhariev/ngx-uploadx/blob/5d946e5cf4032f58e58c176998ca0f11858da08b/src/uploadx/lib/uploadx.service.ts#L18-L31

2022-04-20 06:28 UTC, Chocobozzz commented
@kukhariev It's used to calculate `progress`: https://github.com/kukhariev/ngx-uploadx/blob/master/src/uploadx/lib/uploader.ts#L280

And `undefined + 30 = NaN` so we still have a `NaN` for the first progress state

2022-04-20 10:44 UTC, kukhariev commented
Thanks!, should be fixed by #374